version: "2"
linters:
  default: all
  disable:
    - depguard
    - err113
    - exhaustruct
    - funlen
    - lll
    - musttag
    - perfsprint
    - testpackage
    - varnamelen
    - wsl
    - wsl_v5
  settings:
    misspell:
      locale: US
  exclusions:
    presets:
      - std-error-handling
formatters:
  enable:
    - gofmt
    - gofumpt
    - goimports
