services:
  test-certs-site:
    build: .
    volumes:
      - test-certs-site-config:/config:ro
      - ./integration/pebble.minica.pem:/pebble.minica.pem
      - test-certs-data:/data
    environment:
      LEGO_CA_CERTIFICATES: /pebble.minica.pem
    command: ["/test-certs-site", "-config", "/config/test-certs-site-config.json"]
    depends_on:
      configgen:
        condition: service_completed_successfully
    ports:
      - "5001:5001"
      - "9001:9001"
    networks:
      testnet:
        aliases:
          - valid.localhost
          - revoked.localhost
          - expired.localhost

  configgen:
    build:
      context: .
      dockerfile: integration/configgen/Dockerfile
    volumes:
      - ./integration/pebble.minica.pem:/pebble.minica.pem:ro
      - test-certs-site-config:/config
    command:
      - "-roots-url=https://pebble:15000/roots/0"
      - "-minica=/pebble.minica.pem"
      - "-output=/config/test-certs-site-config.json"
    depends_on:
      - pebble
    networks:
      - testnet

  pebble:
    image: ghcr.io/letsencrypt/pebble
    command: -config /pebble-config.json
    volumes:
      - ./integration/pebble-config.json:/pebble-config.json
    ports:
      - "14000:14000"
      - "15000:15000"
    networks:
      - testnet

networks:
  testnet:
    driver: bridge


volumes:
  test-certs-data:
  test-certs-site-config:
